### PR TITLE
Mock one

### PR DESCRIPTION
**Pull request by tanzila-abedin**
hi 

kIndy  review up to what I have done. I am not done with the project yet. My approach was to finish html first then start with css. which took up more time than I expected. I am hoping to complete my project by tomorrow night.
I haven't set up my repository incorrect order as well.
Thank you

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
# REQUIRES CHANGES :o: 
Great job adding HTML page structure.
Semantic HTML elements have been used throughout the page.
Let's make some changes before we move on.

## REQUIRED
* The main lesson to be learned from this project is the ability to position elements using on the page. Let's add some styles to our page.
* Let's set up [GitHub actions configuration files](https://github.com/microverseinc/linters-config/tree/master/html-css) and make sure the code passes linter checks.
* Let's make the README file more descriptive.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by tanzila-abedin** [comment]
Hi 

I have made all the necessary you changes you have asked for.
kindly have a look.

thank you.

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @tanzila-abedin :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this project. However your code review request is marked as invalid due to the following reasons:
1. Make sure that you fix all of linters
Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by tanzila-abedin** [comment]
Good day @descholar-ceo 
 
All linter errors are clear now. Kindly approve my project if there are no necessary changes to be made.

Thank you

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑 

## Hello team 👋,

**Great job implementing the requested changes.**

### Highlights

- **Linters are properly configured.**
- **The theory of inflation section looks like the original.**

### Mandatory requirements

1). **Ensure the font colors match those of the original page. You have used blue instead of dark colors. Also, your texts, even though they are links, should not be underlined.**

2). **Fix the background color for the subscribe and login buttons.**

3). **The design for the social media icons at the top and bottom of the page should look like the original.**

4). **The alignment of image captions in the More in space and Astronomy and Editor's pick sections is not properly done. For example, the top caption is way too far on the right. It should instead align with the bottom right side of the image.**

5). **Fix the Read 615 comments so it looks like the original. For example, your button has too much padding at the bottom.**

6). **The new york logo in the footer should be a link.**

7). **The last column in the footer should have icons. Also, the first four list items should have a bold / bolder font-weight.**

8). **Please create a professional README file. Hint you can use this [template](https://github.com/microverseinc/readme-template) from Microverse.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Comment by tanzila-abedin** [comment]
Hello 
I have made the changes you asked for. kindly approve my project.

thank you.

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 

Hello there. Thanks for your hard work and your page looks good but before moving on there are some things that need to be done. :smile: 

original1

- [ ] Up above the original page. Your page writings have different sizes on widths. Kindly make it one column as on the original page. Also, place the editor's pick on the right side to where it belongs which is more to left. closer to the central column.
student1

orignal2

- [ ]  Up above you can see the original page, that is above the footer. Your page doesn't look like the original and laying to the left. Kindly make it centered and decrease the width.
student2

original3

- [ ] Up above you can see the original footer. Your footer doesn't look like this. Kindly fix this issue by decreasing the width of the footer and make it centered.
student3

You've used flex and grid and I think you've understood the logic. You can do these changes easily. :100: After making those changes please submit the PR for another review.

If you have any questions about the review, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by tanzila-abedin** [comment]
Hello, I have made the changes. Kindly approve it.

thank you

**Review by krys2fa — CHANGES_REQUESTED** [review]
## Nicely done @tanzila-abedin  👏 
You have done so well implementing all the requested changes. 💪 

### Status: Changes Required ♻️ 

- [ ] [REQUIRED] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


Please request another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Comment by tanzila-abedin** [comment]
Hello 
it is on the main branch. if I create another readme file on the current branch it conflicts with the main branch.

**Comment by tanzila-abedin** [comment]
Screenshot from 2021-02-20 19-45-42

**Review by krys2fa — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the main branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best @tanzila-abedin,
Chris

**Pull request merged**
